Test status trial 2

diff --git a/.github/workflows/run_all_examples.yaml b/.github/workflows/run_all_examples.yaml
--- a/.github/workflows/run_all_examples.yaml
+++ b/.github/workflows/run_all_examples.yaml
@@ -256,5 +256,7 @@ jobs:
           #     done
           #   } >> "$GITHUB_STEP_SUMMARY"
           # fi
-          exit "$STATUS"
+          # If any errors, fail the step
+          if [ "$STATUS" -eq 1 ]; then
+            exit 1
 
